### ISSUE TITLE
Copy to clipboard on left-click

### ISSUE THREAD

**Issue by Cwpute** [phts/firefox-special-characters#21]
Would save quite some time if it was possible to copy a character to the clipboard (or paste it directly into the current field the cursor/carret is in) with a simple left click on it.

**Comment by phts** [comment]
Now if you click on any cell in the table it will copy value of the cell into clipboard. Green checkmark appears as confirmation.

**Comment by Cwpute** [comment]
that was fast ! incredible, thanks :)

**Comment by phts** [comment]
it was there since long time ago already 😉
